name: Code Analysis
on:
  pull_request:
    branches:
      - develop
jobs:
  code-analysis:
    runs-on: macos-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download & Copy local.properties
        run: |
          curl -o local.properties "${{ secrets.LOCAL_PROPERTIES_URL }}"
          mv local.properties ./local.properties
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
        continue-on-error: true
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true


