name: Code Analysis
on:
  pull_request:
    branches:
      - develop
  #       TODO Re-use this bit
jobs:
  setup-properties:
    runs-on: macos-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download & Copy local.properties
        run: |
          curl -o local.properties "${{ secrets.LOCAL_PROPERTIES_URL }}"
          mv local.properties ./local.properties

  code-analysis:
    runs-on: macos-latest
    needs: setup-properties
    steps:
      #       TODO Re-use the checkout and setup-java steps from the update-dependencies-action.yml file
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
        continue-on-error: true
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true


