name: Update Dependencies
on:
  schedule:
    - cron: '30 16 * * 3'
jobs:
  version-update:
    runs-on: macos-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download & Copy local.properties
        run: |
          curl -o local.properties "${{ secrets.LOCAL_PROPERTIES_URL }}"
          mv local.properties ./local.properties
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Version Update
        run: |
          ./gradlew versionCatalogUpdate

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Version Catalog"
          body: "Automated version update using GitHub Actions."
          commit-message: "Update version catalog"
